---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    user: ${CURRENT_UID}
    ports:
      - 8443:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brussels/UTC
      - SUDO_PASSWORD=localadmin
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - .:/config/workspace
      - ./data:/config/data
      - .vscode/extensions.json:/config/extensions/extensions.json
      - ~/.ssh/id_rsa:/config/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/config/.ssh/id_rsa.pub
      - ~/.gitconfig:/etc/gitconfig
